Commands:
  isSuicideEnabled: true
  isGMEnabled: true
  isHomeEnabled: true
  isCarryEnabled: true
  isSendCordsEnabled: true
  isLDLEnabled: true
  isCoordsEnabled: true
  isWarpEnabled: true
  isNickEnabled: true
  isEnderChestEnabled: true
  isCraftingTableEnabled: true
  isAnvilEnabled: true
  isFlightEnabled: true
  worlds: true
Misc:
  enableSkinRefresher: true
  isBedrockBridgeBuildEnabled: true
  isSizeEnabled: true
  isSitEnabled: true
  isCrawlEnabled: true
  isBellEnabled: true
  isLeashEnabled: true
  isFastSleepEnabled: true
  FastSleepPercentage: 50
  areSuggestionsEnabled: true
  CommandsList: true
  isTPAEnabled: true
  TPATimer: 120 #Expressed in seconds
  MinecartSpawn: true
Economy:
  isEnabled: true
  symbol: '$'
ResourcePacks:
  isEnabled: true
  forcePack: false
  #you can find the configuration file for this function in the ResourcePacks folder
Chunks:
  ChunkLoader: true
  XpFarmChunks: true
World:
  doChestRefill: false
  chestRefillTimer: 1800 #Seconds between refills, 1800s=30m
  doPersonalChestLoot: false
AdminUtils:
  canUseFreeze: false
  enableAreas: false
  isInvseeEnabled: true
  isRELEnabled: true
  UpdateTellToOps: false
  areChestsEnabled: true
  replaceChestsWithBarrels: false
  Commands:
    RemoveMinecart: true
    RemoveProjectiles: true
    RemoveStands: true
    EntityList: true
  Values:
    #-1 means infinite
    MaxMinecartChunk: 20
    MaxMinecartWorld: 200
    MaxMinecartServer: -1
    MaxStandChunk: 20
    MaxStandWorld: 200
    MaxStandServer: -1
    MaxProjectileChunk: 60
    MaxProjectileWorld: 600
    MaxProjectileServer: -1
Backup:
  Enabled: true
  AutomaticBackups: true
  BKTimer: 20 #Expressed in minutes, backs up all the worlds
  NumOfBackups: 5
KnockDown:
  isEnabled: true
  Timer: 20 #Expressed in seconds, time before a knocked player will die. A negative number represents an infinite amount of time
ClearLag:
  EnableItemsCheck: true
  CheckTimer: 10 #Expressed in minutes
  MaxAmountOfEntitiesInChunk: 20
  OPsVerbose: false
Roles:
  Enable: true
#DO NOT TOUCH THIS
ConfigVersion: 28.62