Commands:
  isSuicideEnabled: true
  isGMEnabled: true
  isRELEnabled: true
  isHomeEnabled: true
  isCarryEnabled: true
  isSendCordsEnabled: true
  isLDLEnabled: true
  isChunkLoaderEnabled: true
  isCoordsEnabled: true
  isTPAEnabled: true
  isWarpEnabled: true
  isNickEnabled: true
  isEnderChestEnabled: true
  isCraftingTableEnabled: true
  isInvseeEnabled: true
  isAnvilEnabled: true
  isFlightEnabled: true
Misc:
  isSizeEnabled: true
  isSitEnabled: true
  isBellEnabled: true
  isLeashEnabled: true
  FastSleep: true
  FastSleepPercentage: 50
  areSuggestionsEnabled: true
  CommandsList: true
  TPATimer: 120 #Expressed in seconds
Worlds:
  isEnable: true
Economy:
  isEnabled: true
  symbol: '$'
ResourcePacks:
  isEnabled: true
  forcePack: false
  #you can find the configuration file for this function in the ResourcePacks folder
AdminUtils:
  UpdateTellToOps: false
  Commands:
    RemoveMinecart: true
    RemoveProjectiles: true
    RemoveStands: true
    EntityList: true
  Values:
    #-1 means infinite
    MaxMinecartChunk: 20
    MaxMinecartWorld: 200
    MaxMinecartServer: -1
    MaxStandChunk: 20
    MaxStandWorld: 200
    MaxStandServer: -1
    MaxProjectileChunk: 60
    MaxProjectileWorld: 600
    MaxProjectileServer: -1
Backup:
  Enabled: true
  AutomaticBackups: true
  BKTimer: 20 #Expressed in minutes, backs up all the worlds
  NumOfBackups: 5
#DO NOT TOUCH THIS
ConfigVersion: 24.0