name: EveryThingPlugin
version: 0.7.4.1
main: it.plugin.Plugin
api-version: 1.20.6
author: il_maranna
description: A Plugin meant to include as much features as possible
load: POSTWORLD
commands:
  oa:
    usage: /command
    description: allows players to open anvil on the go
  projectile-cleaner:
    usage: /command
    description: Removes every projectile in excess to the max set in the config
  stand-cleaner:
    usage: /command
    description: Removes every armor stand in excess to the max set in the config
  minecart-cleaner:
    usage: /command
    description: Removes every minecart in excess to the max set in the config
  el:
    usage: /command
    description: Report how many entities are loaded
  invsee:
    usage: /command player
    description: Allows ops to open player's inventories
    permission: commands.invsee
  ct:
    usage: /command
    description: Allows players to open a crafting table on the go
  ec:
    usage: /command player
    description: Allows players to open their enderchest on the go
  warp:
    usage: /command LocationName|add|remove LocationName
    description: Allow players to teleport to  locations
    permission: commands.warp
  tpa:
    usage: /command player|allow|deny ApplicantPlayer
    description: Allows players to teleport near other player
    permission: commands.tpa
  suicide:
    usage: /command
    description: Set Player Health to 0
    permission: commands.suicide
  rel:
    usage: /command config|server|all
    description: Reload the server and the plugin
    permission: misc.rel
  gm:
    usage: /command
    description: Cycles between spectator and survival mode
    permission: commands.gm
  info:
    usage: /command
    description: Sends info about the plugin creator and version
    permission: commands.info
  home:
    usage: /command set|remove
    description: Basic home command
    permission: commands.home
  balance:
    usage: /command send|add|sub|set AllPlayers amount
    aliases: [bal, money]
    description: Balance system command
    permission: economy.command
  carry:
    usage: /command player
    description: Make a player ride the player who used the command
    permission: misc.carry
  ldl:
    usage: /command
    description: Sends the last death location to a player
    permission: commands.ldl
  sendposition:
    usage: /command player
    description: Send to another player your current position
    permission: commands.sendposition
  coords:
    usage: /command toNether|toOverworld
    description: Translate the overworld coordinates to nether ones and vice versa
    permission: commands.coords
  chunk:
    usage: /command load|unload|list all|world|nether|end chunkX chunkX
    description: Commands for the chunk loader feature
    permission: chunkloader.command
  suggestion:
    usage: /command
    description: Allows players to give the server owner suggestions for the server itself
    permission: commands.suggestion
  commands:
    usage: /command
    description: Gives a list including all Plugin's commands
    permission: commands.list
permissions:
  commands.*:
    children:
      commands.invsee:
        default: op
      commands.warp: true
      commands.suicide: true
      commands.coords: true
      commands.sendposition: true
      commands.ldl: true
      commands.home: true
      commands.gm: true
      commands.list: true
      commands.suggestion: true
      commands.info: true
      commands.tpa: true
      commands.nick: true
    default: true
  commands.nick:
    default: true
    description: Allows players to use the nick command and change their nicks
    children:
      commands.nick.changeothers: true
  commands.nick.changeothers:
    default: op
    description: Allows ops to change other players nicknames
  commands.warp:
    default: true
    description: Allows players to use the warp command and teleport themselves
    children:
      commands.warp.set:
        default: op
        description: allows ops to create warp points
      commands.warp.all:
        default: op
        description: allows ops to teleport all players in one location
  commands.tpa:
    default: true
    description: Allows players to use the tpa command
  commands.suicide:
    default: true
    description: Allows players to use the suicide command
  commands.coords:
    default: true
    description: Allows players to use the coords command
  commands.sendposition:
    default: true
    description: Allows players to use the sendposition command
  commands.ldl:
    default: true
    description: Allows players to use the last death location command
  commands.home:
    default: true
    description: Allows players to use the home command
  commands.gm:
    default: true
    description: Allows players to use the game mode switch command
  commands.list:
    default: true
    description: Allows players to use the commands command
  commands.suggestion:
    default: true
    description: Allows players to use the suggestion command
  commands.info:
    default: true
    description: Allows players to use the info command
  misc.*:
    children:
      misc.rel: true
      misc.carry: true
    default: op
  misc.rel:
    default: op
    description: Allows ops to reload the server or the plugin config (or both)
  misc.carry:
    default: op
    description: Allows players to carry others (only ops for now)
  economy.*:
    children:
      economy.command: true
    default: true
  economy.command:
    default: true
    description: Allows players to do simple transactions